### ISSUE TITLE
feat: Integrate ef-test to the CI

### ISSUE THREAD

**Issue by bajpai244** [kkrt-labs/kakarot#730]
# Feature Request

**Describe the Feature Request**

We are currently doing ef-tests in parallel, we some tests passing, and we as we finding bugs, we are updating the Kakarot source, we would not want any new changes being made to Kakarot to break any compatibility with any passing EF tests, hence we should integrate ef-tests in the CI.

**Describe Preferred Solution**

The flow looks like the following:
- on every PR start a CI job
- download the [dump-katana](https://github.com/kkrt-labs/kakarot-rpc/blob/main/crates/core/src/test_utils/bin/dump-katana.rs) binary in the CI
- take the builds of the current Kakarot contracts
- make dump-katana create a dump from these builds
- download the binary of the ef-test runner
- execute the runner with this binary

```mermaid
flowchart TD
    A[on every PR] -->| start a CI job | B( CI JOB ) 
    B -->|1| C[ download katana-dump ]
    B -->|2| D[ build kakarot ]
    B -->|3| E[ build dumps ]
    B -->|4| F[ download ef-test runner ]
    B -->|5| G[ run tests with runner ]
```

**If the feature request is approved, would you be willing to submit a PR?**
Yes  🥕 
```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/ef-tests/issues/75
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/530
```

**Comment by Eikix** [comment]
What is the status of this track? Are we tracking the progress of adding ef-tests to the kakarot CI?

**Comment by Eikix** [comment]
proposed flow:
- create a workflow in the .github
- the flow should create a dump
- git clone ef-tests
- build (cache)
- make ef-tests

**Comment by jobez** [comment]
I have an idea about how debuggers can include the relevant suite in the ef-tests run on PR. To start out, we can have a convention in the structure of the PR name that is used to be passed to the ef-tests to not skip a particular suite that the debugger is aiming to make pass.

gpt'ed yaml:

```
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-specified-suite:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Extract suite from PR Title
        id: extract-suite
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          SUITE_TO_RUN=$(echo "$PR_TITLE" | grep -oP '\[Run Suite: \K[^]]+')
          echo "::set-output name=suite::$SUITE_TO_RUN"
          
      - name: Run suite
        if: steps.extract-suite.outputs.suite != ''
        run: |
          SUITE="${{ steps.extract-suite.outputs.suite }}"
          echo "Running Suite: $SUITE"
          # Execute the necessary commands or scripts to run the specified suite
```

This would need a corresponding PR in ef-tests to have an environment variable read that specifies to run a currently failing (and thus skipped) suite.
